/**
 * =========================================================
 * 📌 الملف: قاموس ومحرك اللغات الشامل (Global i18n Config)
 * 📁 المسار: src/config/languages.js
 * 📝 الوظيفة: دعم 15 لغة عالمية مع تحديد الاتجاه وقاموس
 *            ترجمة شامل يغطي الجداول، الأزرار، والواجهات.
 * =========================================================
 */

export const LANGUAGES = [
  { code: "ar", name: "العربية", flag: "🇪🇬", dir: "rtl" },
  { code: "en", name: "English", flag: "🇺🇸", dir: "ltr" },
  { code: "fr", name: "Français", flag: "🇫🇷", dir: "ltr" },
  { code: "es", name: "Español", flag: "🇪🇸", dir: "ltr" },
  { code: "de", name: "Deutsch", flag: "🇩🇪", dir: "ltr" },
  { code: "it", name: "Italiano", flag: "🇮🇹", dir: "ltr" },
  { code: "ru", name: "Русский", flag: "🇷🇺", dir: "ltr" },
  { code: "zh", name: "中文", flag: "🇨🇳", dir: "ltr" },
  { code: "ja", name: "日本語", flag: "🇯🇵", dir: "ltr" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷", dir: "ltr" },
  { code: "fa", name: "فارسی", flag: "🇮🇷", dir: "rtl" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳", dir: "ltr" },
  { code: "pt", name: "Português", flag: "🇵🇹", dir: "ltr" },
  { code: "ur", name: "اردو", flag: "🇵🇰", dir: "rtl" },
  { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩", dir: "ltr" }
];

export const TRANSLATIONS = {
  ar: {
    appName: "نظام إدارة الأقساط والمبيعات",
    welcome: "مرحباً،",
    generalSupervisor: "المشرف العام",
    logout: "تسجيل الخروج",
    addClient: "إضافة عميل جديد",
    pay: "سداد الأقساط",
    search: "استعلام عن عميل",
    monthlyDues: "مستحقات هذا الشهر",
    lateClients: "المتأخرين عن السداد",
    deleteClient: "حذف حساب عميل",
    treasury: "توزيع الأرباح والخزينة",
    treasuryPartners: "الشركاء ورأس المال",
    treasuryEmployees: "شؤون الموظفين والرواتب",
    settings: "الإعدادات والصلاحيات",
    backup: "النسخ الاحتياطي السحابي",
    exit: "خروج",
    netProfit: "صافي الأرباح حتى اليوم",
    netProfitSub: "إجمالي أرباح العقود والتحصيلات الصافية",
    monthlyDuesSub: "المطلوب تحصيله حالياً",
    totalPortfolio: "إجمالي الأقساط المتبقية",
    totalPortfolioSub: "المبالغ المتبقية في ذمة العملاء",
    currency: "ج.م",
    selectLang: "اختر لغة البرنامج",
    selectTheme: "معرض الثيمات والمظهر",
    appThemes: "الثيمات",
    saveSuccess: "تم حفظ بيانات العقد بنجاح بالسحابة!",
    updateSuccess: "تم تحديث البيانات سحابياً بنجاح!",
    loadingCloud: "جاري جلب البيانات من السحابة...",

    // شاشة الاستعلام والجداول
    clientQueryTitle: "استعلام عن عميل",
    activeContracts: "العقود النشطة",
    archivedContracts: "أرشيف العقود المسددة بالكامل",
    openFullRegisterExcel: "فتح سجل بيانات العملاء الشامل - نمط Excel",
    printArchive: "طباعة الأرشيف",
    printRegister: "طباعة سجل العملاء",
    exitDashboard: "خروج والعودة للشاشة الرئيسية",
    searchPlaceholder: "ابحث باسم العميل أو رقم التليفون أو السلعة...",
    searchArchivePlaceholder: "ابحث في أرشيف العقود المسددة...",

    // عناوين أعمدة الجداول
    idHeader: "ID #",
    clientNameHeader: "اسم العميل",
    clientPhoneHeader: "تليفون العميل",
    guarantorNameHeader: "اسم الضامن",
    guarantorPhoneHeader: "تليفون الضامن",
    itemHeader: "السلعة",
    costPriceHeader: "سعر التكلفة",
    salePriceHeader: "سعر البيع",
    downPaymentHeader: "المقدم",
    monthlyInstallmentHeader: "القسط الشهري",
    contractDateHeader: "تاريخ التعاقد",
    firstPayDateHeader: "تاريخ أول قسط",
    notesHeader: "ملاحظات",
    totalCollectedHeader: "إجمالي المحصل",
    totalRemainingHeader: "إجمالي الأقساط المتبقية",
    contractStatusHeader: "حالة العقد",

    // أزرار الكارت والتعديل
    editClientData: "تعديل بيانات العميل",
    saveChanges: "حفظ التعديلات",
    cancel: "إلغاء",
    back: "رجوع",
    contractActiveStatus: "عقد جار وتحديد الأقساط مستمر",
    contractPaidStatus: "عقد مسدد بالكامل 🎉",
    allClientsRegisterTitle: "سجل بيانات العملاء الشامل",
    archiveTitle: "إيجيمود لإدارة الأقساط - أرشيف العقود المسددة",
    noDataFound: "لا توجد نتائج مطابقة للبحث حالياً"
  },
  en: {
    appName: "Pro Installment Management System",
    welcome: "Welcome,",
    generalSupervisor: "General Supervisor",
    logout: "Logout",
    addClient: "Add New Client",
    pay: "Pay Installments",
    search: "Client Inquiry",
    monthlyDues: "Current Month Dues",
    lateClients: "Late Clients",
    deleteClient: "Delete Client Account",
    treasury: "Treasury & Profits",
    treasuryPartners: "Partners & Capital",
    treasuryEmployees: "Employees & Salaries",
    settings: "Settings & Permissions",
    backup: "Cloud Backup",
    exit: "Exit",
    netProfit: "Net Profit To Date",
    netProfitSub: "Total net contract and collection profits",
    monthlyDuesSub: "Total amount to collect currently",
    totalPortfolio: "Total Remaining Portfolio",
    totalPortfolioSub: "Remaining client balances",
    currency: "EGP",
    selectLang: "Select Language",
    selectTheme: "Themes Gallery",
    appThemes: "Themes",
    saveSuccess: "Contract saved successfully to cloud!",
    updateSuccess: "Data updated successfully in cloud!",
    loadingCloud: "Loading data from cloud...",

    // Client Query & Tables
    clientQueryTitle: "Client Inquiry",
    activeContracts: "Active Contracts",
    archivedContracts: "Fully Paid Contracts Archive",
    openFullRegisterExcel: "Open Full Client Register - Excel Mode",
    printArchive: "Print Archive",
    printRegister: "Print Register",
    exitDashboard: "Exit to Main Dashboard",
    searchPlaceholder: "Search by client name, phone, or item...",
    searchArchivePlaceholder: "Search paid contracts archive...",

    // Table Headers
    idHeader: "ID #",
    clientNameHeader: "Client Name",
    clientPhoneHeader: "Client Phone",
    guarantorNameHeader: "Guarantor Name",
    guarantorPhoneHeader: "Guarantor Phone",
    itemHeader: "Item",
    costPriceHeader: "Cost Price",
    salePriceHeader: "Sale Price",
    downPaymentHeader: "Down Payment",
    monthlyInstallmentHeader: "Monthly Installment",
    contractDateHeader: "Contract Date",
    firstPayDateHeader: "First Pay Date",
    notesHeader: "Notes",
    totalCollectedHeader: "Total Collected",
    totalRemainingHeader: "Total Remaining",
    contractStatusHeader: "Contract Status",

    // Actions & Card Text
    editClientData: "Edit Client Data",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    back: "Back",
    contractActiveStatus: "Active Contract & Ongoing Collection",
    contractPaidStatus: "Fully Paid Contract 🎉",
    allClientsRegisterTitle: "Comprehensive Client Register",
    archiveTitle: "Egymod Installments - Paid Contracts Archive",
    noDataFound: "No matching results found"
  },
  fr: {
    appName: "Système de Gestion des Versements",
    welcome: "Bienvenue,",
    generalSupervisor: "Superviseur Général",
    logout: "Déconnexion",
    addClient: "Nouveau Client",
    pay: "Payer les Versements",
    search: "Recherche Client",
    monthlyDues: "Cotisations du Mois",
    lateClients: "Clients en Retard",
    deleteClient: "Supprimer Client",
    treasury: "Trésorerie & Profits",
    treasuryPartners: "Associés & Capital",
    treasuryEmployees: "Personnel & Salaires",
    settings: "Paramètres",
    backup: "Sauvegarde Cloud",
    exit: "Quitter",
    netProfit: "Bénéfice Net",
    netProfitSub: "Bénéfices nets totaux",
    monthlyDuesSub: "Montant à collecter",
    totalPortfolio: "Portefeuille Restant",
    totalPortfolioSub: "Solde restant des clients",
    currency: "EGP",
    selectLang: "Choisir la Langue",
    selectTheme: "Galerie de Thèmes",
    appThemes: "Thèmes",
    saveSuccess: "Contrat enregistré sur le cloud!",
    updateSuccess: "Mise à jour réussie!",
    loadingCloud: "Chargement depuis le cloud...",
    clientQueryTitle: "Enquête Client",
    activeContracts: "Contrats Actifs",
    archivedContracts: "Archives Payées",
    openFullRegisterExcel: "Registre Complet Excel",
    printArchive: "Imprimer l'Archive",
    printRegister: "Imprimer le Registre",
    exitDashboard: "Retour au Tableau de Bord",
    searchPlaceholder: "Rechercher nom, tél, article...",
    searchArchivePlaceholder: "Rechercher dans les archives...",
    idHeader: "ID #",
    clientNameHeader: "Nom Client",
    clientPhoneHeader: "Tél Client",
    guarantorNameHeader: "Nom Garant",
    guarantorPhoneHeader: "Tél Garant",
    itemHeader: "Article",
    costPriceHeader: "Prix Coût",
    salePriceHeader: "Prix Vente",
    downPaymentHeader: "Acompte",
    monthlyInstallmentHeader: "Mensualité",
    contractDateHeader: "Date Contrat",
    firstPayDateHeader: "1ère Échéance",
    notesHeader: "Notes",
    totalCollectedHeader: "Total Perçu",
    totalRemainingHeader: "Total Restant",
    contractStatusHeader: "Statut",
    editClientData: "Modifier le Client",
    saveChanges: "Enregistrer",
    cancel: "Annuler",
    back: "Retour",
    contractActiveStatus: "Contrat Actif",
    contractPaidStatus: "Contrat Payé 🎉",
    allClientsRegisterTitle: "Registre Général des Clients",
    archiveTitle: "Archives des Contrats Payés",
    noDataFound: "Aucun résultat trouvé"
  },
  es: {
    appName: "Sistema de Gestión de Cuotas",
    welcome: "Bienvenido,",
    generalSupervisor: "Supervisión General",
    logout: "Cerrar Sesión",
    addClient: "Agregar Cliente",
    pay: "Pagar Cuotas",
    search: "Consulta de Cliente",
    monthlyDues: "Cuotas del Mes",
    lateClients: "Clientes Morosos",
    deleteClient: "Eliminar Cliente",
    treasury: "Tesorería y Ganancias",
    treasuryPartners: "Socios y Capital",
    treasuryEmployees: "Empleados y Salarios",
    settings: "Configuración",
    backup: "Copia en la Nube",
    exit: "Salir",
    netProfit: "Ganancia Neta",
    netProfitSub: "Ganancias netas acumuladas",
    monthlyDuesSub: "Monto a cobrar actual",
    totalPortfolio: "Cartera Pendiente",
    totalPortfolioSub: "Saldos pendientes de clientes",
    currency: "EGP",
    selectLang: "Seleccionar Idioma",
    selectTheme: "Galería de Temas",
    appThemes: "Temas",
    saveSuccess: "¡Guardado en la nube con éxito!",
    updateSuccess: "¡Datos actualizados!",
    loadingCloud: "Cargando desde la nube...",
    clientQueryTitle: "Consulta de Clientes",
    activeContracts: "Contratos Activos",
    archivedContracts: "Archivo de Liquidados",
    openFullRegisterExcel: "Registro Completo Excel",
    printArchive: "Imprimir Archivo",
    printRegister: "Imprimir Registro",
    exitDashboard: "Volver al Panel Principal",
    searchPlaceholder: "Buscar por nombre, tel, artículo...",
    searchArchivePlaceholder: "Buscar en el archivo...",
    idHeader: "ID #",
    clientNameHeader: "Nombre Cliente",
    clientPhoneHeader: "Teléfono Cliente",
    guarantorNameHeader: "Nombre Garante",
    guarantorPhoneHeader: "Teléfono Garante",
    itemHeader: "Artículo",
    costPriceHeader: "Precio Costo",
    salePriceHeader: "Precio Venta",
    downPaymentHeader: "Enganche",
    monthlyInstallmentHeader: "Cuota Mensual",
    contractDateHeader: "Fecha Contrato",
    firstPayDateHeader: "1er Pago",
    notesHeader: "Notas",
    totalCollectedHeader: "Total Cobrado",
    totalRemainingHeader: "Total Pendiente",
    contractStatusHeader: "Estado Contrato",
    editClientData: "Editar Cliente",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    back: "Volver",
    contractActiveStatus: "Contrato Activo en Cobro",
    contractPaidStatus: "Contrato Liquidado 🎉",
    allClientsRegisterTitle: "Registro General de Clientes",
    archiveTitle: "Archivo de Contratos Pagados",
    noDataFound: "No se encontraron resultados"
  },
  de: {
    appName: "Ratenzahlungs-Verwaltungssystem",
    welcome: "Willkommen,",
    generalSupervisor: "Hauptadministrator",
    logout: "Abmelden",
    addClient: "Kunde Hinzufügen",
    pay: "Raten Zahlen",
    search: "Kundenabfrage",
    monthlyDues: "Monatsbeiträge",
    lateClients: "Säumige Kunden",
    deleteClient: "Konto Löschen",
    treasury: "Finanzen & Gewinne",
    treasuryPartners: "Partner & Kapital",
    treasuryEmployees: "Personal & Gehälter",
    settings: "Einstellungen",
    backup: "Cloud-Sicherung",
    exit: "Beenden",
    netProfit: "Nettogewinn",
    netProfitSub: "Gesamte Nettogewinne",
    monthlyDuesSub: "Aktuell zu kassieren",
    totalPortfolio: "Offenes Portfolio",
    totalPortfolioSub: "Verbleibende Kundensalden",
    currency: "EGP",
    selectLang: "Sprache Wählen",
    selectTheme: "Design-Galerie",
    appThemes: "Designs",
    saveSuccess: "Erfolgreich in der Cloud gespeichert!",
    updateSuccess: "Daten erfolgreich aktualisiert!",
    loadingCloud: "Lade aus der Cloud...",
    clientQueryTitle: "Kundenabfrage",
    activeContracts: "Aktive Verträge",
    archivedContracts: "Bezahlte Verträge",
    openFullRegisterExcel: "Vollständiges Register (Excel)",
    printArchive: "Archiv Drucken",
    printRegister: "Register Drucken",
    exitDashboard: "Zurück zum Dashboard",
    searchPlaceholder: "Suche nach Name, Tel, Artikel...",
    searchArchivePlaceholder: "Im Archiv suchen...",
    idHeader: "ID #",
    clientNameHeader: "Kundenname",
    clientPhoneHeader: "Kunden-Telefon",
    guarantorNameHeader: "Bürgenname",
    guarantorPhoneHeader: "Bürgen-Telefon",
    itemHeader: "Artikel",
    costPriceHeader: "Selbstkosten",
    salePriceHeader: "Verkaufspreis",
    downPaymentHeader: "Anzahlung",
    monthlyInstallmentHeader: "Monatsrate",
    contractDateHeader: "Vertragsdatum",
    firstPayDateHeader: "Erste Zahlung",
    notesHeader: "Notizen",
    totalCollectedHeader: "Gesamt Kassiert",
    totalRemainingHeader: "Restbetrag",
    contractStatusHeader: "Vertragsstatus",
    editClientData: "Kunde Bearbeiten",
    saveChanges: "Speichern",
    cancel: "Abbrechen",
    back: "Zurück",
    contractActiveStatus: "Aktiver Vertrag",
    contractPaidStatus: "Vollständig Bezahlt 🎉",
    allClientsRegisterTitle: "Gesamtes Kundenregister",
    archiveTitle: "Archiv Bezahlter Verträge",
    noDataFound: "Keine Ergebnisse gefunden"
  },
  it: {
    appName: "Sistema Gestione Rate e Vendite",
    welcome: "Benvenuto,",
    generalSupervisor: "Supervisore Generale",
    logout: "Disconnetti",
    addClient: "Nuovo Cliente",
    pay: "Paga Rate",
    search: "Ricerca Cliente",
    monthlyDues: "Quote del Mese",
    lateClients: "Clienti Morosi",
    deleteClient: "Elimina Cliente",
    treasury: "Tassonomia e Profitti",
    treasuryPartners: "Soci e Capitale",
    treasuryEmployees: "Dipendenti e Stipendi",
    settings: "Impostazioni",
    backup: "Backup Cloud",
    exit: "Esci",
    netProfit: "Profitto Netto",
    netProfitSub: "Profitti netti totali",
    monthlyDuesSub: "Da incassare ora",
    totalPortfolio: "Portafoglio Rimanente",
    totalPortfolioSub: "Saldi rimanenti clienti",
    currency: "EGP",
    selectLang: "Seleziona Lingua",
    selectTheme: "Galleria Temi",
    appThemes: "Temi",
    saveSuccess: "Salvato nel cloud!",
    updateSuccess: "Aggiornato con successo!",
    loadingCloud: "Caricamento cloud...",
    clientQueryTitle: "Ricerca Clienti",
    activeContracts: "Contratti Attivi",
    archivedContracts: "Archivio Saldati",
    openFullRegisterExcel: "Registro Completo Excel",
    printArchive: "Stampa Archivio",
    printRegister: "Stampa Registro",
    exitDashboard: "Torna alla Dashboard",
    searchPlaceholder: "Cerca per nome, tel, articolo...",
    searchArchivePlaceholder: "Cerca nell'archivio...",
    idHeader: "ID #",
    clientNameHeader: "Nome Cliente",
    clientPhoneHeader: "Tel Cliente",
    guarantorNameHeader: "Nome Garante",
    guarantorPhoneHeader: "Tel Garante",
    itemHeader: "Articolo",
    costPriceHeader: "Prezzo Costo",
    salePriceHeader: "Prezzo Vendita",
    downPaymentHeader: "Acconto",
    monthlyInstallmentHeader: "Rata Mensile",
    contractDateHeader: "Data Contratto",
    firstPayDateHeader: "1a Scadenza",
    notesHeader: "Note",
    totalCollectedHeader: "Totale Incassato",
    totalRemainingHeader: "Totale Rimanente",
    contractStatusHeader: "Stato Contratto",
    editClientData: "Modifica Cliente",
    saveChanges: "Salva Modifiche",
    cancel: "Annulla",
    back: "Indietro",
    contractActiveStatus: "Contratto Attivo",
    contractPaidStatus: "Completamente Saldato 🎉",
    allClientsRegisterTitle: "Registro Generale Clienti",
    archiveTitle: "Archivio Contratti Saldati",
    noDataFound: "Nessun risultato trovato"
  },
  ru: {
    appName: "Система Управления Рассрочкой",
    welcome: "Добро пожаловать,",
    generalSupervisor: "Главный Инспектор",
    logout: "Выйти",
    addClient: "Добавить Клиента",
    pay: "Оплата Рассрочки",
    search: "Поиск Клиента",
    monthlyDues: "Платежи за Месяц",
    lateClients: "Должники",
    deleteClient: "Удалить Клиента",
    treasury: "Казначейство и Прибыль",
    treasuryPartners: "Партнеры и Капитал",
    treasuryEmployees: "Сотрудники и Зарплата",
    settings: "Настройки",
    backup: "Облачный Бэкап",
    exit: "Выход",
    netProfit: "Чистая Прибыль",
    netProfitSub: "Общая чистая прибыль",
    monthlyDuesSub: "К сбору в этом месяце",
    totalPortfolio: "Остаток Портфеля",
    totalPortfolioSub: "Остаток задолженности",
    currency: "EGP",
    selectLang: "Выберите Язык",
    selectTheme: "Галерея Тем",
    appThemes: "Темы",
    saveSuccess: "Успешно сохранено в облаке!",
    updateSuccess: "Данные обновлены!",
    loadingCloud: "Загрузка из облака...",
    clientQueryTitle: "Поиск и Проверка",
    activeContracts: "Активные Договоры",
    archivedContracts: "Архив Выплаченных",
    openFullRegisterExcel: "Полный Реестр Excel",
    printArchive: "Печать Архива",
    printRegister: "Печать Реестра",
    exitDashboard: "На Главную Панель",
    searchPlaceholder: "Поиск по имени, тел, товару...",
    searchArchivePlaceholder: "Поиск в архиве...",
    idHeader: "ID #",
    clientNameHeader: "Имя Клиента",
    clientPhoneHeader: "Тел. Клиента",
    guarantorNameHeader: "Имя Поручителя",
    guarantorPhoneHeader: "Тел. Поручителя",
    itemHeader: "Товар",
    costPriceHeader: "Себестоимость",
    salePriceHeader: "Цена Продажи",
    downPaymentHeader: "Взнос",
    monthlyInstallmentHeader: "Ежемесячный Платеж",
    contractDateHeader: "Дата Договора",
    firstPayDateHeader: "Первый Платеж",
    notesHeader: "Заметки",
    totalCollectedHeader: "Всего Собрано",
    totalRemainingHeader: "Остаток Долга",
    contractStatusHeader: "Статус",
    editClientData: "Редактировать",
    saveChanges: "Сохранить",
    cancel: "Отмена",
    back: "Назад",
    contractActiveStatus: "Действующий Договор",
    contractPaidStatus: "Полностью Выплачен 🎉",
    allClientsRegisterTitle: "Полный Реестр Клиентов",
    archiveTitle: "Архив Выплаченных Договоров",
    noDataFound: "Ничего не найдено"
  },
  zh: {
    appName: "分期付款与销售管理系统",
    welcome: "欢迎,",
    generalSupervisor: "总监督员",
    logout: "退出登录",
    addClient: "添加新客户",
    pay: "缴纳分期款",
    search: "客户查询",
    monthlyDues: "本月应收款",
    lateClients: "逾期客户",
    deleteClient: "删除客户账户",
    treasury: "资金与利润分配",
    treasuryPartners: "股东与资本",
    treasuryEmployees: "员工与薪酬",
    settings: "设置与权限",
    backup: "云端备份",
    exit: "退出",
    netProfit: "截至今日净利润",
    netProfitSub: "合同与扣款净利润总额",
    monthlyDuesSub: "当前待收总额",
    totalPortfolio: "剩余总分期额",
    totalPortfolioSub: "客户剩余待还余额",
    currency: "EGP",
    selectLang: "选择系统语言",
    selectTheme: "主题展厅",
    appThemes: "主题",
    saveSuccess: "成功保存至云端！",
    updateSuccess: "云端数据更新成功！",
    loadingCloud: "正在从云端加载数据...",
    clientQueryTitle: "客户查询",
    activeContracts: "进行中合同",
    archivedContracts: "已结清合同归档",
    openFullRegisterExcel: "打开客户完整登记表 (Excel模式)",
    printArchive: "打印归档",
    printRegister: "打印总登记表",
    exitDashboard: "返回主面板",
    searchPlaceholder: "按姓名、电话或商品搜索...",
    searchArchivePlaceholder: "搜索已结清合同...",
    idHeader: "编号 #",
    clientNameHeader: "客户姓名",
    clientPhoneHeader: "客户电话",
    guarantorNameHeader: "担保人姓名",
    guarantorPhoneHeader: "担保人电话",
    itemHeader: "商品",
    costPriceHeader: "成本价",
    salePriceHeader: "售价",
    downPaymentHeader: "首付",
    monthlyInstallmentHeader: "月供",
    contractDateHeader: "签约日期",
    firstPayDateHeader: "首期还款日",
    notesHeader: "备注",
    totalCollectedHeader: "已收总额",
    totalRemainingHeader: "剩余待还",
    contractStatusHeader: "合同状态",
    editClientData: "编辑客户资料",
    saveChanges: "保存修改",
    cancel: "取消",
    back: "返回",
    contractActiveStatus: "合同履约中",
    contractPaidStatus: "已全部结清 🎉",
    allClientsRegisterTitle: "客户综合登记册",
    archiveTitle: "已结清合同归档",
    noDataFound: "未找到匹配结果"
  },
  ja: {
    appName: "分割払い・销售管理システム",
    welcome: "ようこそ、",
    generalSupervisor: "統括管理者",
    logout: "ログアウト",
    addClient: "新規顧客追加",
    pay: "分割払い入金",
    search: "顧客照会",
    monthlyDues: "今月の請求額",
    lateClients: "滞納者一覧",
    deleteClient: "口座削除",
    treasury: "金庫・利益分配",
    treasuryPartners: "パートナー・出資",
    treasuryEmployees: "人事・給与",
    settings: "設定・権限",
    backup: "クラウドバックアップ",
    exit: "終了",
    netProfit: "本日までの純利益",
    netProfitSub: "契約・回収の純利益合計",
    monthlyDuesSub: "現在回収対象額",
    totalPortfolio: "残回収ポートフォリオ",
    totalPortfolioSub: "顧客の残債務合計",
    currency: "EGP",
    selectLang: "言語を選択",
    selectTheme: "テーマギャラリー",
    appThemes: "テーマ",
    saveSuccess: "クラウドへ保存しました！",
    updateSuccess: "更新が完了しました！",
    loadingCloud: "クラウドから読み込み中...",
    clientQueryTitle: "顧客照会",
    activeContracts: "有効な契約",
    archivedContracts: "完済契約アーカイブ",
    openFullRegisterExcel: "全顧客台帳を開く(Excel)",
    printArchive: "アーカイブ印刷",
    printRegister: "台帳印刷",
    exitDashboard: "ダッシュボードに戻る",
    searchPlaceholder: "氏名・電話番号・商品で検索...",
    searchArchivePlaceholder: "完済アーカイブを検索...",
    idHeader: "ID #",
    clientNameHeader: "顧客名",
    clientPhoneHeader: "顧客電話",
    guarantorNameHeader: "保証人名",
    guarantorPhoneHeader: "保証人電話",
    itemHeader: "商品名",
    costPriceHeader: "仕入原価",
    salePriceHeader: "販売価格",
    downPaymentHeader: "頭金",
    monthlyInstallmentHeader: "月額分割金",
    contractDateHeader: "契約日",
    firstPayDateHeader: "初回支払日",
    notesHeader: "備考",
    totalCollectedHeader: "回収済合計",
    totalRemainingHeader: "残債合計",
    contractStatusHeader: "契約ステータス",
    editClientData: "顧客情報を編集",
    saveChanges: "変更を保存",
    cancel: "キャンセル",
    back: "戻る",
    contractActiveStatus: "契約履行中",
    contractPaidStatus: "完済 🎉",
    allClientsRegisterTitle: "全顧客総合台帳",
    archiveTitle: "完済契約アーカイブ",
    noDataFound: "該当するデータがありません"
  },
  tr: {
    appName: "Taksit ve Satış Yönetim Sistemi",
    welcome: "Hoş geldiniz,",
    generalSupervisor: "Genel Süpervizör",
    logout: "Çıkış Yap",
    addClient: "Yeni Müşteri Ekle",
    pay: "Taksit Öde",
    search: "Müşteri Sorgulama",
    monthlyDues: "Bu Ayın Alacakları",
    lateClients: "Geciken Müşteriler",
    deleteClient: "Müşteri Sil",
    treasury: "Hazine ve Kâr Dağıtımı",
    treasuryPartners: "Ortaklar ve Sermaye",
    treasuryEmployees: "Personel ve Maaşlar",
    settings: "Ayarlar ve İzinler",
    backup: "Bulut Yedekleme",
    exit: "Çıkış",
    netProfit: "Net Kâr (Bugüne Kadar)",
    netProfitSub: "Toplam net sözleşme kârları",
    monthlyDuesSub: "Şu an tahsil edilecek",
    totalPortfolio: "Kalan Kredi Portföyü",
    totalPortfolioSub: "Müşteri kalan bakiyeleri",
    currency: "EGP",
    selectLang: "Dil Seçin",
    selectTheme: "Tema Galerisi",
    appThemes: "Temalar",
    saveSuccess: "Buluta başarıyla kaydedildi!",
    updateSuccess: "Veriler güncellendi!",
    loadingCloud: "Buluttan yükleniyor...",
    clientQueryTitle: "Müşteri Sorgulama",
    activeContracts: "Aktif Sözleşmeler",
    archivedContracts: "Ödenmiş Sözleşme Arşivi",
    openFullRegisterExcel: "Tam Müşteri Kaydı (Excel)",
    printArchive: "Arşivi Yazdır",
    printRegister: "Kaydı Yazdır",
    exitDashboard: "Ana Panele Dön",
    searchPlaceholder: "İsim, telefon veya ürünle ara...",
    searchArchivePlaceholder: "Ödenen arşivde ara...",
    idHeader: "ID #",
    clientNameHeader: "Müşteri Adı",
    clientPhoneHeader: "Müşteri Tel",
    guarantorNameHeader: "Kefil Adı",
    guarantorPhoneHeader: "Kefil Tel",
    itemHeader: "Ürün",
    costPriceHeader: "Maliyet Fiyatı",
    salePriceHeader: "Satış Fiyatı",
    downPaymentHeader: "Peşinat",
    monthlyInstallmentHeader: "Aylık Taksit",
    contractDateHeader: "Sözleşme Tarihi",
    firstPayDateHeader: "İlk Ödeme Tarihi",
    notesHeader: "Notlar",
    totalCollectedHeader: "Toplam Tahsil Edilen",
    totalRemainingHeader: "Toplam Kalan",
    contractStatusHeader: "Sözleşme Durumu",
    editClientData: "Müşteriyi Düzenle",
    saveChanges: "Değişiklikleri Kaydet",
    cancel: "İptal",
    back: "Geri",
    contractActiveStatus: "Aktif Ödeme Süreci",
    contractPaidStatus: "Tamamen Ödendi 🎉",
    allClientsRegisterTitle: "Kapsamlı Müşteri Kaydı",
    archiveTitle: "Ödenen Sözleşmeler Arşivi",
    noDataFound: "Eşleşen sonuç bulunamadı"
  },
  fa: {
    appName: "سیستم مدیریت اقساط و فروش",
    welcome: "خوش آمدید،",
    generalSupervisor: "سرپرست کل",
    logout: "خروج از حساب",
    addClient: "افزودن مشتری جدید",
    pay: "پرداخت اقساط",
    search: "استعلام مشتری",
    monthlyDues: "مطالبات این ماه",
    lateClients: "مشتریان بدهکار",
    deleteClient: "حذف حساب مشتری",
    treasury: "خزانه‌داری و سودها",
    treasuryPartners: "شرکا و سرمایه",
    treasuryEmployees: "کارکنان و حقوق",
    settings: "تنظیمات و دسترسی‌ها",
    backup: "پشتیبان‌گیری ابری",
    exit: "خروج",
    netProfit: "سود خالص تا امروز",
    netProfitSub: "مجموع سودهای خالص قراردادها",
    monthlyDuesSub: "مبلغ قابل وصول فعلی",
    totalPortfolio: "کل اقساط باقی‌مانده",
    totalPortfolioSub: "باقیمانده بدهی مشتریان",
    currency: "پوند",
    selectLang: "انتخاب زبان برنامه",
    selectTheme: "گالری تم‌ها",
    appThemes: "تم‌ها",
    saveSuccess: "با موفقیت در ابر ذخیره شد!",
    updateSuccess: "اطلاعات به‌روزرسانی شد!",
    loadingCloud: "در حال دریافت اطلاعات ابری...",
    clientQueryTitle: "استعلام مشتری",
    activeContracts: "قراردادهای فعال",
    archivedContracts: "آرشیو تسویه‌شده‌ها",
    openFullRegisterExcel: "دفتر جامع مشتریان (اکسل)",
    printArchive: "چاپ آرشیو",
    printRegister: "چاپ دفتر کل",
    exitDashboard: "بازگشت به داشبورد اصلی",
    searchPlaceholder: "جستجو با نام، تلفن یا کالا...",
    searchArchivePlaceholder: "جستجو در آرشیو تسویه‌شده...",
    idHeader: "شناسه #",
    clientNameHeader: "نام مشتری",
    clientPhoneHeader: "تلفن مشتری",
    guarantorNameHeader: "نام ضامن",
    guarantorPhoneHeader: "تلفن ضامن",
    itemHeader: "کالا",
    costPriceHeader: "قیمت تمام‌شده",
    salePriceHeader: "قیمت فروش",
    downPaymentHeader: "پیش‌پرداخت",
    monthlyInstallmentHeader: "قسط ماهانه",
    contractDateHeader: "تاریخ قرارداد",
    firstPayDateHeader: "تاریخ اولین قسط",
    notesHeader: "توضیحات",
    totalCollectedHeader: "کل دریافتی",
    totalRemainingHeader: "کل باقیمانده",
    contractStatusHeader: "وضعیت قرارداد",
    editClientData: "ویرایش اطلاعات مشتری",
    saveChanges: "ذخیره تغییرات",
    cancel: "انصراف",
    back: "بازگشت",
    contractActiveStatus: "قرارداد جاری و فعال",
    contractPaidStatus: "کاملاً تسویه شده 🎉",
    allClientsRegisterTitle: "دفتر جامع اطلاعات مشتریان",
    archiveTitle: "آرشیو قراردادهای تسویه‌شده",
    noDataFound: "هیچ نتیجه‌ای یافت نشد"
  },
  hi: {
    appName: "किस्त एवं बिक्री प्रबंधन प्रणाली",
    welcome: "स्वागत है,",
    generalSupervisor: "मुख्य पर्यवेक्षक",
    logout: "लॉग आउट",
    addClient: "नया ग्राहक जोड़ें",
    pay: "किस्त का भुगतान करें",
    search: "ग्राहक पूछताछ",
    monthlyDues: "इस महीने की बकाया राशि",
    lateClients: "बकायादार ग्राहक",
    deleteClient: "खाता हटाएं",
    treasury: "خزانه और लाभ",
    treasuryPartners: "भागीदार और पूंजी",
    treasuryEmployees: "कर्मचारी और वेतन",
    settings: "सेटिंग्स और अनुमति",
    backup: "क्लाउड बैकअप",
    exit: "बाहर निकलें",
    netProfit: "आज तक का कुल शुद्ध लाभ",
    netProfitSub: "कुल शुद्ध अनुबंध लाभ",
    monthlyDuesSub: "वर्तमान में वसूली योग्य",
    totalPortfolio: "कुल शेष किस्तें",
    totalPortfolioSub: "ग्राहकों की शेष राशि",
    currency: "EGP",
    selectLang: "भाषा चुनें",
    selectTheme: "थीम गैलरी",
    appThemes: "थीम्स",
    saveSuccess: "क्लाउड में सफलतापूर्वक सहेजा गया!",
    updateSuccess: "डेटा अद्यतन किया गया!",
    loadingCloud: "क्लाउड से डेटा लोड हो रहा है...",
    clientQueryTitle: "ग्राहक पूछताछ",
    activeContracts: "सक्रिय अनुबंध",
    archivedContracts: "पूर्ण भुगतान संग्रह",
    openFullRegisterExcel: "पूर्ण ग्राहक रजिस्टर (Excel)",
    printArchive: "संग्रह प्रिंट करें",
    printRegister: "रजिस्टर प्रिंट करें",
    exitDashboard: "मुख्य डैशबोर्ड पर लौटें",
    searchPlaceholder: "नाम, फोन या आइटम द्वारा खोजें...",
    searchArchivePlaceholder: "भुगतान किए गए संग्रह में खोजें...",
    idHeader: "आईडी #",
    clientNameHeader: "ग्राहक का नाम",
    clientPhoneHeader: "ग्राहक फोन",
    guarantorNameHeader: "गारंटर का नाम",
    guarantorPhoneHeader: "गारंटर फोन",
    itemHeader: "वस्तु",
    costPriceHeader: "लागत मूल्य",
    salePriceHeader: "बिक्री मूल्य",
    downPaymentHeader: "अग्रिम भुगतान",
    monthlyInstallmentHeader: "मासिक किस्त",
    contractDateHeader: "अनुबंध की तारीख",
    firstPayDateHeader: "पहली किस्त की तारीख",
    notesHeader: "ملاحظات",
    totalCollectedHeader: "कुल एकत्र",
    totalRemainingHeader: "कुल शेष",
    contractStatusHeader: "अनुबंध की स्थिति",
    editClientData: "ग्राहक विवरण संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    cancel: "रद्द करें",
    back: "वापस",
    contractActiveStatus: "सक्रिय अनुबंध और वसूली जारी",
    contractPaidStatus: "पूर्ण भुगतान किया गया 🎉",
    allClientsRegisterTitle: "व्यापक ग्राहक रजिस्टर",
    archiveTitle: "भुगतान किए गए अनुबंधों का संग्रह",
    noDataFound: "कोई परिणाम नहीं मिला"
  },
  pt: {
    appName: "Sistema de Gestão de Prestações",
    welcome: "Bem-vindo,",
    generalSupervisor: "Supervisor Geral",
    logout: "Sair",
    addClient: "Adicionar Cliente",
    pay: "Pagar Prestações",
    search: "Consulta de Cliente",
    monthlyDues: "Mensalidades do Mês",
    lateClients: "Clientes em Atraso",
    deleteClient: "Excluir Cliente",
    treasury: "Tesouraria e Lucros",
    treasuryPartners: "Sócios e Capital",
    treasuryEmployees: "Funcionários e Salários",
    settings: "Configurações",
    backup: "Backup na Nuvem",
    exit: "Sair",
    netProfit: "Lucro Líquido",
    netProfitSub: "Lucros líquidos totais",
    monthlyDuesSub: "A cobrar no momento",
    totalPortfolio: "Carteira Restante",
    totalPortfolioSub: "Saldos devedores restantes",
    currency: "EGP",
    selectLang: "Selecionar Idioma",
    selectTheme: "Galeria de Temas",
    appThemes: "Temas",
    saveSuccess: "Salvo na nuvem com sucesso!",
    updateSuccess: "Dados atualizados!",
    loadingCloud: "Carregando da nuvem...",
    clientQueryTitle: "Consulta de Clientes",
    activeContracts: "Contratos Ativos",
    archivedContracts: "Arquivo de Quitados",
    openFullRegisterExcel: "Registro Completo Excel",
    printArchive: "Imprimir Arquivo",
    printRegister: "Imprimir Registro",
    exitDashboard: "Voltar ao Painel Principal",
    searchPlaceholder: "Buscar por nome, tel, item...",
    searchArchivePlaceholder: "Buscar no arquivo...",
    idHeader: "ID #",
    clientNameHeader: "Nome Cliente",
    clientPhoneHeader: "Tel Cliente",
    guarantorNameHeader: "Nome Fiador",
    guarantorPhoneHeader: "Tel Fiador",
    itemHeader: "Item",
    costPriceHeader: "Preço Custo",
    salePriceHeader: "Preço Venda",
    downPaymentHeader: "Entrada",
    monthlyInstallmentHeader: "Parcela Mensal",
    contractDateHeader: "Data Contrato",
    firstPayDateHeader: "1º Vencimento",
    notesHeader: "Notas",
    totalCollectedHeader: "Total Recebido",
    totalRemainingHeader: "Total Restante",
    contractStatusHeader: "Status do Contrato",
    editClientData: "Editar Cliente",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    back: "Voltar",
    contractActiveStatus: "Contrato Ativo",
    contractPaidStatus: "Totalmente Quitado 🎉",
    allClientsRegisterTitle: "Registro Geral de Clientes",
    archiveTitle: "Arquivo de Contratos Quitados",
    noDataFound: "Nenhum resultado encontrado"
  },
  ur: {
    appName: "اقساط اور فروخت کا انتظام",
    welcome: "خوش آمدید،",
    generalSupervisor: "جنرل سپروائزر",
    logout: "لاگ آؤٹ",
    addClient: "نیا گاہک شامل کریں",
    pay: "اقساط کی ادائیگی",
    search: "گاہک کی معلومات",
    monthlyDues: "اس ماہ کے واجبات",
    lateClients: "تأخیر کرنے والے گاہک",
    deleteClient: "اکاؤنٹ حذف کریں",
    treasury: "خزانہ اور منافع",
    treasuryPartners: "شرکاء اور سرمایہ",
    treasuryEmployees: "ملازمین اور تنخواہیں",
    settings: "ترتیبات اور اختیارات",
    backup: "کلاؤڈ بیک اپ",
    exit: "باہر نکلیں",
    netProfit: "آج تک کا خالص منافع",
    netProfitSub: "معاہدوں کا کل خالص منافع",
    monthlyDuesSub: "موجودہ قابل وصول رقم",
    totalPortfolio: "کل باقی اقساط",
    totalPortfolioSub: "گاہکوں کے باقی واجبات",
    currency: "پاؤنڈ",
    selectLang: "زبان منتخب کریں",
    selectTheme: "تھیم گیلری",
    appThemes: "تھیمز",
    saveSuccess: "کلاؤڈ میں کاملاً محفوظ ہو گیا!",
    updateSuccess: "معلومات اپ ڈیٹ ہو گئیں!",
    loadingCloud: "کلاؤڈ سے ڈیٹا لوڈ ہو رہا ہے...",
    clientQueryTitle: "گاہک کی معلومات",
    activeContracts: "فعال معاہدے",
    archivedContracts: "مکمل ادا شدہ آرکائیو",
    openFullRegisterExcel: "مکمل گاہک رجسٹر (ایکسل)",
    printArchive: "آرکائیو پرنٹ کریں",
    printRegister: "رجسٹر پرنٹ کریں",
    exitDashboard: "مین ڈیش بورڈ پر واپس جائیں",
    searchPlaceholder: "نام، فون یا سامان سے تلاش کریں...",
    searchArchivePlaceholder: "ادا شدہ آرکائیو میں تلاش کریں...",
    idHeader: "آئی ڈی #",
    clientNameHeader: "گاہک کا نام",
    clientPhoneHeader: "گاہک کا فون",
    guarantorNameHeader: "ضامن کا نام",
    guarantorPhoneHeader: "ضامن کا فون",
    itemHeader: "سامان",
    costPriceHeader: "لاگت کی قیمت",
    salePriceHeader: "فروخت کی قیمت",
    downPaymentHeader: "پیشگی ادائیگی",
    monthlyInstallmentHeader: "ماہانہ قسط",
    contractDateHeader: "معاہدے کی تاریخ",
    firstPayDateHeader: "پہلی قسط کی تاریخ",
    notesHeader: "نوٹس",
    totalCollectedHeader: "کل وصول شدہ",
    totalRemainingHeader: "کل باقی",
    contractStatusHeader: "معاہدے کی حالت",
    editClientData: "معلومات ترمیم کریں",
    saveChanges: "ترمیم محفوظ کریں",
    cancel: "منسوخ کریں",
    back: "واپس",
    contractActiveStatus: "فعال معاہدہ اور وصولی جاری",
    contractPaidStatus: "مکمل ادا شدہ 🎉",
    allClientsRegisterTitle: "جامع گاہک رجسٹر",
    archiveTitle: "ادا شدہ معاہدوں کا آرکائیو",
    noDataFound: "کوئی نتائج نہیں ملے"
  },
  id: {
    appName: "Sistem Manajemen Angsuran",
    welcome: "Selamat datang,",
    generalSupervisor: "Supervisi Umum",
    logout: "Keluar",
    addClient: "Tambah Pelanggan",
    pay: "Bayar Angsuran",
    search: "Pencarian Pelanggan",
    monthlyDues: "Tagihan Bulan Ini",
    lateClients: "Pelanggan Menunggak",
    deleteClient: "Hapus Akun",
    treasury: "Kas & Pembagian Keuntungan",
    treasuryPartners: "Mitra & Modal",
    treasuryEmployees: "Karyawan & Gaji",
    settings: "Pengaturan & Izin",
    backup: "Cadangan Cloud",
    exit: "Keluar",
    netProfit: "Laba Bersih Hingga Saat Ini",
    netProfitSub: "Total laba bersih kontrak",
    monthlyDuesSub: "Total penagihan saat ini",
    totalPortfolio: "Sisa Portofolio Angsuran",
    totalPortfolioSub: "Sisa saldo piutang pelanggan",
    currency: "EGP",
    selectLang: "Pilih Bahasa",
    selectTheme: "Galeri Tema",
    appThemes: "Tema",
    saveSuccess: "Berhasil disimpan ke cloud!",
    updateSuccess: "Data berhasil diperbarui!",
    loadingCloud: "Memuat dari cloud...",
    clientQueryTitle: "Pencarian Pelanggan",
    activeContracts: "Kontrak Aktif",
    archivedContracts: "Arsip Kontrak Lunas",
    openFullRegisterExcel: "Buka Register Lengkap (Excel)",
    printArchive: "Cetak Arsip",
    printRegister: "Cetak Register",
    exitDashboard: "Kembali ke Dashboard Utama",
    searchPlaceholder: "Cari berdasarkan nama, telp, barang...",
    searchArchivePlaceholder: "Cari arsip lunas...",
    idHeader: "ID #",
    clientNameHeader: "Nama Pelanggan",
    clientPhoneHeader: "Telp Pelanggan",
    guarantorNameHeader: "Nama Penjamin",
    guarantorPhoneHeader: "Telp Penjamin",
    itemHeader: "Barang",
    costPriceHeader: "Harga Pokok",
    salePriceHeader: "Harga Jual",
    downPaymentHeader: "Uang Muka",
    monthlyInstallmentHeader: "Angsuran Bulanan",
    contractDateHeader: "Tanggal Kontrak",
    firstPayDateHeader: "Jatuh Tempo Ke-1",
    notesHeader: "Catatan",
    totalCollectedHeader: "Total Terkumpul",
    totalRemainingHeader: "Total Sisa",
    contractStatusHeader: "Status Kontrak",
    editClientData: "Edit Data Pelanggan",
    saveChanges: "Simpan Perubahan",
    cancel: "Batal",
    back: "Kembali",
    contractActiveStatus: "Kontrak Aktif & Penagihan Berjalan",
    contractPaidStatus: "Lunas Sepenuhnya 🎉",
    allClientsRegisterTitle: "Register Pelanggan Komprehensif",
    archiveTitle: "Arsip Kontrak Lunas",
    noDataFound: "Hasil tidak ditemukan"
  }
};
